### PR TITLE
Fix SwiftUI Previews in Xcode 14

### PR DESCRIPTION
**Pull request by rafaelcalunga**
Things to consider before you submit the PR:

* [x] Are tests passing locally?
* [x] Are the files formatted correctly?
* ~~[ ] Did you add unit tests?~~
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

This PR fixes SwiftUI Previews in Xcode 14 that failed to run when adding **Azure Notification Hubs SDK** through SPM.

## Related PRs or issues

The fix is based on this [PR](https://github.com/microsoft/appcenter-sdk-apple/pull/2433) from **Visual Studio App Center SDK**.

## Misc

This PR fixes the following issue:

An iOS project doesn't work anymore for SwiftUI Preview with Xcode 14.
The project builds and runs fine, but Preview never works. The error message is as follows:

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060001f8fee80):'WindowsAzureMessaging'>)
```

Azure Notification Hubs SDK is added thought SPM.
SwiftUI Preview with Xcode 13 works.

More information about the issue in Xcode 14 can be seen in this [Apple Developer forum thread](https://developer.apple.com/forums/thread/707569).

### CODE REVIEW

**Comment by rafaelcalunga** [comment]
@microsoft-github-policy-service agree

**Review by Daniebro5Bluetread — APPROVED** [review]

**Review by menteValidus — APPROVED** [review]
AppCenter team came to the same solution.

**Comment by brannon** [comment]
@rafaelcalunga thanks for the PR submission. I'll take a look and make sure this doesn't have any unintended side-effects.

**Comment by brannon** [comment]
@rafaelcalunga I spent some time researching the issue, and looking at the change made to the AppCenter SDK. 

While removing the `.type` from the Swift library seems to workaround the Xcode issue, I'm concerned that changing the library type in the Swift package would be a breaking change for existing consumers of the package.

I noticed that AppCenter also released this change as part of a new major library version (see [AppCenter PR #2439](https://github.com/microsoft/appcenter-sdk-apple/pull/2439)), which suggests they were also concerned with breaking existing consumers.

[Several developers are reporting that Xcode 14.2 resolves the SwiftUI preview issue](https://developer.apple.com/forums/thread/707569?answerId=739343022#739343022). That would be preferable to changing the library type.

Can you confirm if you've tried with Xcode 14.2?

**Comment by rafaelcalunga** [comment]
@brannon I am happy to report that Xcode 14.2 appears to have resolved this issue for my apps.

Version 14.2 (14C18)
WindowsAzureMessaging 3.1.5

**Comment by brannon** [comment]
@rafaelcalunga thank you for confirming!

**Pull request closed without merging**
