### PR TITLE
Add UserId methods to NotificationHub class

### PR DESCRIPTION
**Pull request by varvusc**

### CODE REVIEW

**Comment by iTOYS** [comment]
Add comparison here
https://github.com/Azure/azure-notificationhubs-ios/pull/86/files#diff-23c94a10981b69f0cd25f46555b17cb4L220

**Comment by mpodwysocki** [comment]
@varvusc can you rebase and merge the changes from master?

**Comment by iTOYS** [comment]
> @varvusc can you rebase and merge the changes from master?

I'll do

**Comment by iTOYS** [comment]
> @varvusc can you rebase and merge the changes from master?

Done!

**Pull request merged**
